### PR TITLE
Implement hidding of extra gcc/stl symbols

### PR DESCRIPTION
**Pull request by malaterre**

### CODE REVIEW

**Comment by vbaderks** [comment]
In which situation are these extra symbols exported? I am only seeing the charls_* + 4 legacy with readelf.

**Comment by malaterre** [comment]
You may need a full Debian system to reproduce. On my side:

```
$ debuild -B
...
dpkg-gensymbols: error: some new symbols appeared in the symbols file: see diff output below
dpkg-gensymbols: warning: debian/libcharls2/DEBIAN/symbols doesn't match completely debian/libcharls2.symbols
--- debian/libcharls2.symbols (libcharls2_2.3.1+dfsg-1_amd64)
+++ dpkg-gensymbols5S5x9O       2022-01-27 07:41:40.289111254 +0100
@@ -3,6 +3,23 @@
  JpegLsDecodeRect@Base 2.0.0+dfsg
  JpegLsEncode@Base 2.0.0+dfsg
  JpegLsReadHeader@Base 2.0.0+dfsg
+ _ZNSt12_Vector_baseIaSaIaEED1Ev@Base 2.3.1+dfsg-1
+ _ZNSt12_Vector_baseIaSaIaEED2Ev@Base 2.3.1+dfsg-1
+ _ZNSt12_Vector_baseIhSaIhEED1Ev@Base 2.3.1+dfsg-1
+ _ZNSt12_Vector_baseIhSaIhEED2Ev@Base 2.3.1+dfsg-1
+ _ZNSt12_Vector_baseIiSaIiEED1Ev@Base 2.3.1+dfsg-1
+ _ZNSt12_Vector_baseIiSaIiEED2Ev@Base 2.3.1+dfsg-1
+ _ZNSt12_Vector_baseItSaItEED1Ev@Base 2.3.1+dfsg-1
+ _ZNSt12_Vector_baseItSaItEED2Ev@Base 2.3.1+dfsg-1
+ _ZNSt6vectorIaSaIaEE17_M_default_appendEm@Base 2.3.1+dfsg-1
+ _ZNSt6vectorIaSaIaEE6resizeEm@Base 2.3.1+dfsg-1
+ _ZNSt6vectorIaSaIaEED1Ev@Base 2.3.1+dfsg-1
+ _ZNSt6vectorIaSaIaEED2Ev@Base 2.3.1+dfsg-1
+ _ZNSt6vectorIhSaIhEE17_M_realloc_insertIJRKhEEEvN9__gnu_cxx17__normal_iteratorIPhS1_EEDpOT_@Base 2.3.1+dfsg-1
+ _ZNSt6vectorIhSaIhEEC1EmRKS0_@Base 2.3.1+dfsg-1
+ _ZNSt6vectorIhSaIhEEC2EmRKS0_@Base 2.3.1+dfsg-1
+ _ZNSt6vectorItSaItEEC1EmRKS0_@Base 2.3.1+dfsg-1
+ _ZNSt6vectorItSaItEEC2EmRKS0_@Base 2.3.1+dfsg-1
  charls_get_error_message@Base 2.1.0+dfsg
  charls_get_jpegls_category@Base 2.1.0+dfsg
  charls_get_version_number@Base 2.1.0+dfsg
```

**Comment by malaterre** [comment]
Actual command being run above is:

```
% dpkg-gensymbols  -plibcharls2 -edebian/libcharls2/usr/lib/x86_64-linux-gnu/libcharls.so.2.3.1
```

**Comment by malaterre** [comment]
Starring at the code, it seems to be around here:

* https://git.dpkg.org/cgit/dpkg/dpkg.git/tree/scripts/dpkg-gensymbols.pl#n214

**Comment by malaterre** [comment]
Turns out I was able to remove the line:

```
-      __gnu_cxx::*;
```

**Pull request merged**
