### PR TITLE
Add LITTLE_ENDIAN_ARCHITECTURE macro (#168)

### PR DESCRIPTION
**Pull request by malaterre**
See commit: 461df4b0e640726f3a7030a9a79bd5735aa258f4

### CODE REVIEW

**Comment by malaterre** [comment]
@vbaderks I'd like to have your blessing for the following patch. I'd like to backport 461df4b0e640726f3a7030a9a79bd5735aa258f4 for release 2.2.0 (currently in Debian stable). Thanks for your review.

**Comment by vbaderks** [comment]
Hi @malaterre into which branch do you want this commit merged? Do you a need a releases/2.2.0 branch?
Or do you want to merge this commit in your own repro. If you create a PR for your own branch, you can also request a review from me.

**Comment by malaterre** [comment]
I believe the right solution is to have a `2.2.x-master` branch. At this time I anticipate a single commit (this one), but we'll see if security team ever found an issue in this branch.

Let me know if you agree with the naming convention, and I'll try to prepare a new PR asap.

**Comment by vbaderks** [comment]
created branch release/2.2x 
Note: the plan is rename "master" into "main" and 1.x-master into release/1.x.x around the next major release

**Comment by malaterre** [comment]
What's the big deal nowadays to rename "master" into "main"... oh well

**Comment by vbaderks** [comment]
Will provide some fixes to the CI and the changelog

**Pull request merged**
