### PR TITLE
Fix a clang warning about an undefined template

### PR DESCRIPTION
**Pull request by malaterre**
Should fix issue #22

### CODE REVIEW

**Comment by vbaderks** [comment]
Hi,

Do you know which C++ v03 compiler can't handle the "extern template class" and would require 
CHARLS_USE_EXTERN_TEMPLATES?

**Comment by vbaderks** [comment]
It seems to be C++ v11 construction:
https://isocpp.org/wiki/faq/cpp11-language-templates

As the 1.x-master branch targets the C++ v03 standard, it would make the code not compatible. The "problem" makes the compile process a little slower (not sure if that is measurable) but would have no effect on the final output.
Why not disable the warning with the -Wno-undefined-func-template?

**Comment by vbaderks** [comment]
General question, which warning option(s) are you using?

**Comment by malaterre** [comment]
Interesting comment ! I'll check with the cmake people on how to mark a library C++98 only. This may hopefully mark `-Wno-undefined-func-template` as no-op.

**Comment by vbaderks** [comment]
Hi Mathieu,

Did you get some feedback from the cmake people, I like to close this pull request.

Victor

**Comment by vbaderks** [comment]
Closing this pull request, due lack of feedback / too old.

**Pull request closed without merging**
